@server = https://signol04-fantastic-tribble-9v4prjq59rvf75rg-8080.preview.app.github.dev/
@emp = {{server}}/api/employees
###
GET {{emp}}
###
POST {{emp}}
Content-Type: application/json

{
    "firstName": "Ozuna",
    "lastName": "Baggins",
    "description": "burglar"
}